### ISSUE TITLE
Example apps don't seem to be compatible with latest mattermost server

### ISSUE THREAD

**Issue by GCHQDeveloper926** [mattermost/mattermost-plugin-apps#309]
Just been trying to get some of the app framework stood up to create an app under the developer preview. I can't seem to get any of the apps (golang or js) working with the latest developer docker image for mattermost-server or the previous ones for the last few weeks. 

Is this just me or is there some updates that need to happen - have looked for docs etc and happy to try and PR the changes if someone can point me to them. 

![image](https://user-images.githubusercontent.com/66307263/159296572-20b9ee1f-7868-45ae-a0b8-8356333a6c8f.png)

**Comment by GCHQDeveloper926** [comment]
I can get mattermost to respond differently if I mess up the manifest input so I know its hitting my local app serve but not sure why its not liking the app type. I'm just using the manifest from the examples repo here.

**Comment by mickmister** [comment]
@GCHQDeveloper926 We are approaching the stable version 1.0 of the Apps framework. At the moment, there are some inconsistencies among the default developer environment configuration.

You will need to manually deploy the master branch of the Apps framework in order to have the latest changes that the examples are using. There are some instructions on how to do this here https://github.com/mattermost/mattermost-plugin-apps/tree/master/dev#updating-versions-of-the-apps-plugin-or-mattermost-server. Let me know if this helps, though it's possible you've already tried this.

Thanks for using the framework to create your own App! Please let me know of any further questions you have. Feel free to join the Mattermost Apps channel on our community server to discuss more with the team https://community.mattermost.com/core/channels/mattermost-apps

**Comment by rovnyart** [comment]
Just faced the same problem. I have Mattermost omnibus installation, installed Apps plugin from marketplace - not working (Error: is not a valid app type: invalid input). Then I uninstalled plugin, got master brach, created distro (make dist), uploaded it to my MM instance via Upload Plugin button, enabled - and now i have no '/apps' command for some reason. It just doesnt work, seems like it's not registered at all. Installing plugin from Marketplace helps - '/apps' command appeares again, but nothing works because of error :(

**Comment by hanzei** [comment]
The apps plugin is now bundled with MM and enabled by default. There should not be any compatibility issues any longer.
